server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3308/board
    username: root
    password: 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show_sql: true
jwt:
  expirationAt: 1000 #1000λ¶„ μ„Έν…
#  jinhoaccesstokenjinhoaccesstokenjinhoaccesstokenjinhoaccesstoken
  secretKeyAt: amluaG9hY2Nlc3N0b2tlbmppbmhvYWNjZXNzdG9rZW5qaW5ob2FjY2Vzc3Rva2VuamluaG9hY2Nlc3N0b2tlbg==

logging:
  level:
#    trace < debug < info < error
    root: info